services:
  tech-challenge-backend:
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env

  tech-challenge-frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: ./
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://tech-challenge-backend:8888
    depends_on:
      - tech-challenge-backend
